# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e8033a63ce08f877ae87a50aa37c6a1"
name = "Shipping Discount"
handle = "shipping-discount-70"
application_url = "https://shipdeals2-main-pc1she.laravel.cloud/"
embedded = true

[build]
dev_store_url = "payrules-final.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://shipdeals2-main-pc1she.laravel.cloud/authenticate"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/webhook/customers-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhook/customers-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhook/shop-redact"
  compliance_topics = [ "shop/redact" ]

[pos]
embedded = false
